### ISSUE TITLE
use on multi-label 3D medical image segmentation task?

### ISSUE THREAD

**Issue by xwjBupt** [CoinCheung/pytorch-loss#11]
Hi, thanks for your outstanding work!  

Can your losses, for example focal loss, be used on multi-label 3D medical image segmentation task?

thank you so much! Look forward of your reply~

**Comment by CoinCheung** [comment]
Hi, 

Focal loss would be fine, since it is point-wise loss, and each sample is considered as a binary classification problem. As for other losses, I am afraid that they are not designed for 3d operations, but you might try to reform your problem and see if the 3d loss can be expressed in a 2d form. Good luck !!

**Comment by CoinCheung** [comment]
I am closing this. You can leave messages if you need further discussions.
