### ISSUE TITLE
partial_fc_amsoftmax memory leak

### ISSUE THREAD

**Issue by tianxingyzxq** [CoinCheung/pytorch-loss#33]
partial_fc_amsoftmax memory leak @CoinCheung

**Comment by tianxingyzxq** [comment]
RuntimeError: CUDA out of memory, after several step

**Comment by tianxingyzxq** [comment]
my torch vision is 1.8.1

**Comment by CoinCheung** [comment]
It is not likely to be leakage problem since I only use pytorch native operators(I did not write cuda kernels for it). Besides, I myself is training my model with it now, and I observe no such problem.

It is also not likely to be problem of optimizers. Would you please provide detail configuration of your platform and description of how to reproduce it?

**Comment by CoinCheung** [comment]
Have you tried to use a small batch size and did you observe memory usage is increasing every iteration？

**Comment by tianxingyzxq** [comment]
I try to reproduce it, and find there is no memory leak at all. My origin train script is wrong. sorry to bother you.
